### ISSUE TITLE
🐛 [format.pretty] breaks delta

### ISSUE THREAD

**Issue by boris-petrov** [dandavison/delta#174]
Hi, thanks for making this! Still got a few bugs but once they are fixed, that would be an indispensable tool!

I have in my `.gitconfig`:

```gitconfig
[format]
	pretty = %C(blue)%H%C(red) %an %C(green)%ad%C(yellow)%d%n%B
[core]
	pager = delta --commit-color=blue --file-color=yellow --file-style=box --hunk-color=purple --hunk-style=plain --theme=none
```

The `[format]` part seems to break `delta`. When I do a `git log -p`, the first line (commit hash, committer, date) is fine however the rest are colorless. The style is preserved as I've specified in `format` though. What can I do about it?

Delta 0.1.1.

**Comment by kbd** [comment]
This is present in 0.4.3.

Here's a screenshot of my custom `git log` with a `-p`:

![Screen Shot 2020-09-24 at 10 37 17 PM](https://user-images.githubusercontent.com/728060/94227092-9ecd9e80-feb6-11ea-85a8-002041026a2a.png)

The "install gomp" in the second commit in the screenshot is incorrectly rendered as if it's a diff, including line numbers.

**Comment by ryuta69** [comment]
I think this one is already resolved?

<img width="918" alt="ss 2" src="https://user-images.githubusercontent.com/41639488/96079055-cb416d00-0eee-11eb-84d9-1cfe622d11dd.png">

Not sure where it fixes, but maybe at version 0.1.1, this condition couldn't catch the Meta so that they don't continue.

https://github.com/dandavison/delta/blob/9732c888eea48038f4d34d67a80999907a04ee50/src/delta.rs#L146-L148

**Comment by ryuta69** [comment]
@boris-petrov 

I think this one is already resolved?

<img width="918" alt="ss 2" src="https://user-images.githubusercontent.com/41639488/96079055-cb416d00-0eee-11eb-84d9-1cfe622d11dd.png">

Not sure where it fixes, but maybe at version 0.1.1, this condition couldn't catch the Meta so that they don't continue.

https://github.com/dandavison/delta/blob/9732c888eea48038f4d34d67a80999907a04ee50/src/delta.rs#L146-L148

delta: v0.4.4

**Comment by boris-petrov** [comment]
Yes, I believe this is fixed. Thanks!

**Comment by kbd** [comment]
Confirmed the behavior is fixed in 0.4.4 vs 0.4.3. Thanks!

**Comment by kbd** [comment]
I apologize, my earlier message was incorrect. I tested with `git log -p`, which always worked. My custom log format, with `git l -p`, still shows incorrect formatting:

![Screen Shot 2020-10-15 at 10 36 19 AM](https://user-images.githubusercontent.com/728060/96159892-74c63580-0ed2-11eb-9982-cbdf35c3e162.png)

**Comment by kbd** [comment]
The log format alias above is:

```l = log --date=format:'%a %Y-%m-%d %k:%M' --color=always --pretty=format:'%C(green)%ad %C(blue)%an %C(auto)%h%d%n %s%n%w(0,4,4)%+b%C(reset)' --stat```

**Comment by ryuta69** [comment]
@kbd 
Ah, I know see that's a bug, thank you for detail.

@dandavison 
I think this is caused because of this code.
https://github.com/dandavison/delta/blob/9cf186c49b3969c21a1cab432bafdc87cf566292/src/delta.rs#L90-L92

If I fix here forcibly (wrong approach. I'm doing like `if line.contains(" ryuta69 ")`), this can be fixed like below.
<img width="587" alt="ss 4" src="https://user-images.githubusercontent.com/41639488/96168971-73d9e600-0f5c-11eb-9e6d-5357bb19728b.png">

Not sure **how to detect if this is CommitMeta**, but if I come up with good idea, will fix.

**Comment by Mellbourn** [comment]
What is broken for me is that the commit line is not formatted correctly for `log -p` and `reflog -p` (it does not get any "box").

The workaround I've found is to add the word `commit` in the log line. So configuring these git aliases in `.gitconfig` displays `log -p` and `reflog -p` correctly:

```
[alias]
	logp = log -p --format='commit %C(yellow)%h %C(magenta)%<(15,trunc)%an %C(cyan)%cd %C(auto)%d%Creset %s'
	reflogp = reflog -p --format='commit %C(auto)%h%d %gd: %gs (%s)'
```

**Comment by dandavison** [comment]
Hi @Mellbourn, by default git does include the word `commit` in `git log -p` output, so this should be working correctly for you (indeed, I use `git log -p` a lot). On the other hand I agree that delta isn't handling `git reflog` very well, as you say!

I wonder what's going on with your `git log -p`. Is it possible that you have another alias altering the default git log output?

**Comment by Mellbourn** [comment]
I should have mentioned: I have a custom `format.pretty` in my `.gitconfig` to make `git log` look good and be more concise. That format does not have the word `commit` in it:

```
[format]
	pretty = %C(yellow)%h %C(magenta)%<(15,trunc)%an %C(cyan)%cd %C(auto)%d%Creset %s
```

Sample output:
<img width="815" alt="nicely formatted git log" src="https://user-images.githubusercontent.com/1785727/113947838-d4f7bd80-980b-11eb-9e97-c676eb4975cb.png">

**Comment by dandavison** [comment]
Ah, OK. Right, your example challenges delta to explain itself a bit! I mean, delta (being `GIT_PAGER`) has to handle every single line of output from git; not just diffs. And it promises to parse that output and decorate things. And yet, git itself encourages the structure of the output to be heavily customized. You can see that what delta does is extremely simple:

https://github.com/dandavison/delta/blob/e7d1e281ea539adb91a57c6945dea123fff1bd16/src/delta.rs#L114

So, what shall we do? I'm open to delta having fairly crazy technical options -- it is a tool for programmers after all -- as long as it doesn't affect performance / UX in the default case. We could perhaps allow users to supply their own regular expression to match key sections of the output such as the commit line to be decorated? Or perhaps delta could inspect the `format.pretty` and derive a regular expression from that? But there's perhaps no way to make that work for `[alias]` entries? If anyone reading feels like this area sounds fun to have a go at, please do shout out.

**Comment by Mellbourn** [comment]
Sounds to me like we would get the most gain for the least effort by allowing users to supply their own regular expressions.

**Comment by dandavison** [comment]
> Sounds to me like we would get the most gain for the least effort by allowing users to supply their own regular expressions.

Yes, I agree.

**Comment by dandavison** [comment]
That seems to have been a simple change. https://github.com/dandavison/delta/pull/558 if you would like to try it out. So for your example, something like `git -c delta.commit-regex='^[0-9a-f]{8} ' log` will work.

<table><tr><td><img width=800px src="https://user-images.githubusercontent.com/52205/113957123-ac140000-97ec-11eb-92d1-78edfe58b911.png" alt="image" /></td></tr></table>

**Comment by kbd** [comment]
I've often thought it's a shame that the separator characters included in ASCII are never used. They'd be a natural fit here if git had used them to delimit structure in `git log`. Eg. if a record separator preceded every commit it would save ad-hoc "starts with 'commit '" parsing.

I suppose that'd be the best way to use the regex with a custom log format? Add a separator character to the beginning of your log format and look for that in the regex?

**Comment by dandavison** [comment]
@kbd I think you could use a record separator character (thanks, I do sometimes use zero-width space for hacks but I wasn't familiar with the ASCII record separators). On the other something ad-hoc like this works for [your](https://github.com/kbd/setup/commit/7caf0b33642638e0c2d4507020bd861e8824c9ae) `l` alias:

```
git -c delta.commit-regex='> [0-9a-f]{7,}$'
```

**Comment by dandavison** [comment]
`commit-regex` is released now (delta 0.8.0)
