### ISSUE TITLE
🐛  Using `--hyperlink`, commit hashes are only clickable when at least of length 8

### ISSUE THREAD

**Issue by chrisgrieser** [dandavison/delta#1923]
```bash
# commit hashes are not clickable
git log -n5 --abbrev=7 

# they are clickable now
git log -n5 --abbrev=8
```

This is kinda unfortunate, since 7 seems to be the default output length by git, meaning you have to explicitly set the length to 8 to make it work.

**Comment by dandavison** [comment]
Hi @chrisgrieser,

> 7 seems to be the default output length by git

Do you have `log.abbrev-commit` set in your git config? I see that makes it defaults to 7, so maybe it would make sense for our lower bound to be 7.

**Comment by chrisgrieser** [comment]
No, I haven't, 7 seems just to be the ootb default for me

**Comment by th1000s** [comment]
Indeed, if the number of objects isn't to large the commit hashes can be abbreviated to 7 characters. Git will only use longer prefixes when needed. Fixed in #1924

**Comment by kaarel-sm** [comment]
This still doesn't work for me.

`git log --format=format:'%h %s' -n2`
Default %h commit hashes are 7 chars and not clickable

`git log --format=format:'%h %s' -n2 --abbrev=8`
Commit hashes are now 8 chars and clickable

git version 2.51.2.windows.1
delta 0.18.2
