### ISSUE TITLE
🐛 Markdown coloring problem

### ISSUE THREAD

**Issue by kjmph** [dandavison/delta#281]
I noticed when delta is used to color Markdown files, it shortens the frag to fit into a fixed width. However, if the frag was a link (which is often the case in Markdown), it messes up the coloring by not stopping the link coloring:

<img width="1440" alt="Screen Shot 2020-08-07 at 9 59 47 AM" src="https://user-images.githubusercontent.com/1075649/89664941-1e66c600-d895-11ea-80a8-de280d30c442.png">

Is there anything else I can supply for this issue?

**Comment by kjmph** [comment]
I notice that I upgraded to 0.4.3, and I still see this behavior. Anything I can do to help?

**Comment by dandavison** [comment]
Hi @kjmph, thanks! Sorry to be slow, this does clearly look like a bug. It suggests that the highlighter is retaining state between the frag and the code, which should be easy to fix.

By the way, do you have anything special configured for your markdown highlighting? I wanted to reproduce your example, but in a very brief attempt I see that bat and delta are only highlighting HTML chunks in markdown files for me.

**Comment by kjmph** [comment]
Sorry my slow response! I suppose I have ran the `bat cache --build` command, because I have a few syntaxes that I haven't taken the time to open a PR for bat yet. However, none of them are related to Markdown. I see there were a few Markdown related changes around May? Perhaps it is due to me building the cache from bat's master branch?

**Comment by dandavison** [comment]
@kjmph sorry not to have fixed this yet.... Ok, I've found a way to reproduce this. Here I've captured some diff output and doctored it to have a hunk header ("frag") that will trigger the bug you've reported:

```diff
diff --git a/README.md b/README.md
index f1db9d6..ddeeff3 100644
--- a/README.html
+++ b/README.html
@@ -14,6 +14,8 @@ <img width=500px src="https://
   <img width=500px src="https://user-images.githubusercontent.com/52205/80056404-23745500-84f2-11ea-9ecd-832376faf2f1.png" alt="image" />
 </td></tr></table>

+This is a new line
+
 If you run emacs as a terminal application (`emacs -nw`) and colors are not being rendered correctly, then follow the instructions here: https://www.gnu.org/software/emacs/manual/html_node/efaq/Colors-on-a-TTY.html.
```

Now feeding that to delta on stdin reproduces it:

<table><tr><td><img width=800px src="https://user-images.githubusercontent.com/52205/101296088-654fd280-3819-11eb-9527-6b0ee87148af.png" alt="image" /></td></tr></table>

Thanks very much; I'll fix this.

Incidentally, the reason I wasn't getting detailed markdown highlighting was because my default theme (GitHub, ironically perhaps) doesn't seem to do that. However there is still one thing I'm baffled by: taking delta out of the equation, it seems that your git is giving you hunk headers ("frags") for markdown. But mine is not. For example, with the magit-delta repo at https://github.com/dandavison/magit-delta/commit/b8526f890415374822514e488341d2b706d6bc2f, I insert a new line like you did, and I don't get a hunk header (I just get `@@ -14,6 +14,8 @@`). Do you have a special [gitattributes rule](https://tekin.co.uk/2020/10/better-git-diff-output-for-ruby-python-elixir-and-more) for markdown by any chance?

```
$ git --no-pager diff
diff --git a/README.md b/README.md
index f1db9d6..ddeeff3 100644
--- a/README.md
+++ b/README.md
@@ -14,6 +14,8 @@
   <img width=500px src="https://user-images.githubusercontent.com/52205/80056404-23745500-84f2-11ea-9ecd-832376faf2f1.png" alt="image" />
 </td></tr></table>
 
+This is a new line
+
 If you run emacs as a terminal application (`emacs -nw`) and colors are not being rendered correctly, then follow the instructions here: https://www.gnu.org/software/emacs/manual/html_node/efaq/Colors-on-a-TTY.html.
```

**Comment by dandavison** [comment]
This is fixed in master (not released yet).

**Comment by kjmph** [comment]
Interesting question you posed to me. I tried with a brand new user account (with no configuration), and I still see the hunk header. I tried on macOS and Linux, same deal. The output is mostly the equivalent of using `diff -u -p <old> <new>`. Where `-p` is shorthand for `--show-c-function`, which makes sense that this would be the default given the roots of git.

If anything, I followed the attributes gist you linked, and using the diff parser for Markdown removes the hunk header's context. I don't actually know how to answer your question, other than, no.. I don't think I'm doing anything special here.

**Comment by kjmph** [comment]
Oh, and my apologies, I was so flummoxed by the question; I forgot to say thank you for fixing this. :)

**Comment by kjmph** [comment]
If we go back in time, we see this was added in git v1.3.0: https://github.com/git/git/commit/acb725772964ee11656543a28c303e9aa6d092c5

While it has had a few modifications to date, it is still the default: https://github.com/git/git/blob/bf0a430f70b53f94454692c9ae8ddadd18891aaa/diff.c#L3596

I can see why it is preferred to use git attributes to change the search for the function header, lots more languages out there now.. Yet, any default git config should reproduce this error.

**Comment by dandavison** [comment]
This is released now (v0.4.5).
