### ISSUE TITLE
Setting line numbers in `less` messes up ruler

### ISSUE THREAD

**Issue by alok** [dandavison/delta#61]
See https://github.com/so-fancy/diff-so-fancy/issues/271 for an explanation, since it's the same issue.

**Comment by dandavison** [comment]
If we added a command line option allowing the user to specify how many columns they want delta to use when filling right to the edge of the terminal, do you think that would solve your problem? I haven't fully thought it through, but I did skim your so-fancy/diff-so-fancy#271. Are you seeing the same problem with the background colors extending onto the next line, or just the ruler?

**Comment by alok** [comment]
The background colors also run.

I _think_ it would fix it. I'd be willing to test it out, since I use Rust and can install a branch from git to try it.

**Comment by dandavison** [comment]
OK great, it's on the list. (This would also make a good first issue for anyone who wants a fairly doable Rust task.)

**Comment by dandavison** [comment]
Hi @alok, this should be fixed in `master`: the background colors now adapt dynamically to the terminal width (see 5b2620981bc5d3f4eb13b6b24782e78cfb9f7673) and the horizontal decoration lines now respect the `--width` option.

**Comment by meandmymind** [comment]
I'm still having this.

Have bat as $PAGER and $DELTA_PAGER

when I do `git diff | delta | bat` it's ok
<img width="836" alt="image" src="https://user-images.githubusercontent.com/24773652/145231899-65d49604-c55b-490f-8d6f-6140f625b1e7.png">

when I do just `git diff` with delta set as pager, line is shifted by this `line number column`
<img width="840" alt="image" src="https://user-images.githubusercontent.com/24773652/145232117-28b0b6ff-9904-4d45-9365-ba80084e96ff.png">

**Comment by dandavison** [comment]
Hi @meandmymind, you can solve this by setting delta `width` to a negative value, which means auto-detected width minus $value, e.g.

```gitconfig
[delta]
    width = -9
```

I'm sorry this wasn't documented. The reason was slightly ridiculous -- somehow the wrong sort of comments had got onto two lines of the `cli.rs` modules, so that the relevant two lines of documentation didn't appear in the `--help` output... So thanks for alerting me to that. Fixed in 5ea8dfc4331f072eff4db3e4827e9b7985433a8a and [`--help` output](https://github.com/dandavison/delta#full---help-output) is in README.

**Comment by meandmymind** [comment]
hi @dandavison that's cool!

but why is it happening? I don't have any `less` and `bat` configuration in my system, so "minusing 7" should be default behaviour?

**Comment by dandavison** [comment]
It's because you've got `DELTA_PAGER=bat`. I didn't say anything because I thought it was deliberate, but tbh I did think it was a strange choice :) If you have `PAGER=bat` then you should set `DELTA_PAGER` to something like `less -R`.

**Comment by meandmymind** [comment]
@dandavison ok it means I don't understand this paging stuff but changing `DELTA_PAGER` to `less -R` worked :))) thanks

**Comment by dandavison** [comment]
@meandmymind Would it help if I added something like this to the README? (which maybe should become a user manual one day) I'm not implying that you need all these definitions explained! Trying to make it clear to as many people as possible.

## Glossary

- **terminal emulator**: a graphical application that mimics an old-fashioned text terminal. You run a **shell ** in a terminal emulator (e.g. iTerm2, Gnome Terminal, Konsole, and Alacritty are terminal emulators)
- **shell**: an application that displays a prompt where you can run command line applications (e.g. bash is an example shell)
- **pager**: a command line application that receives text input and displays it one screenful at a time (e.g. less is a pager)
- **less**: the standard pager that is used in linux and unix environments
- **bat**: a command line program that can display source code files with syntax highlighting. `bat` sends its output to `less` for paging
- **delta**: a command line program that can display specialist file formats such as diff, grep, and git blame output, with code syntax highlighting. `delta` also sends its output to `less` for paging
- **environment variable**: a variable that you can set in your shell session
- `PAGER`: an environment variable that can be used to specify the way you want programs to call less, when those programs need to do paging. For example you could do `export PAGER="less -R"` to set this variable: `-R` tells `less` to display colors when its input contains color codes.
- `BAT_PAGER`: an environment variable that you can set to tell `bat` to call `less` differently from the way other programs call `less`
- `DELTA_PAGER`: an environment variable that you can set to tell `delta` to call `less` differently from the way other programs call `less`
- `LESS`: an environment variable that you can set to specify the default arguments `less` should be called with. (Yes, at this point things have got a bit messy! You probably want to ignore this one.)

## Tips
- You don't need to set any environment variables unless doing so fixes a problem for you!
- Use `env` to print out a list of the environment variables you have set, to check that `PAGER`, `BAT_PAGER`, `DELTA`, `LESS` are not set or, if they are set, that they have sensible values.

**Comment by dandavison** [comment]
So to be explicit, what the above glossary is meant to show is that it doesn't make sense to set `DELTA_PAGER=bat` for the following reason: that would mean that `delta` sends its output to `bat`. But `delta`'s output is (typically) in diff format, and the code has already been syntax highlighted, whereas `bat` is expecting source code in some language. So `bat` do anything helpful with `delta`'s output.  But will `bat` do anything undesirable with delta's output? Not if you call it as `bat --plain`, but by default `bat` will put `delta`s output inside ruled margins with line numbers, and that is unlikely to be what you want.

**Comment by meandmymind** [comment]
@dandavison It just wasn't clear to me the relation between delta and bat. Now with your explanations it's much clearear. Thanks!
